# -*- coding: utf-8 -*-

SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = True
SECURITY_RECOVERABLE = True

CHAT_SEARCH_PER_PAGE = 3
CHAT_LIST_PER_PAGE = 20
